[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.13",
    "discord-py>=2.5.2",
    "flask>=3.1.1",
    "yt-dlp>=2024.12.13",
    "PyNaCl>=1.5.0",
    "spotipy>=2.24.0",
]
